### ISSUE TITLE
great package

### ISSUE THREAD

**Issue by timelyportfolio** [XD-DENG/ECharts2Shiny#1]
Great package and excited that you are making eCharts available to R.  Is there a reason for not using the [htmlwidgets](http://htmlwidgets.org) framework?  It would be great to have eCharts available for all R contexts.  Thanks so much for your work on this.

**Comment by XD-DENG** [comment]
Hi @timelyportfolio , thanks so much for your kind words!

This package is derived from my daily works, and I mainly focus on building Shiny dashboards. This is one of the reasons for what I simply wrapped the shiny widgets, instead of using htmlwidgets. 

Another reason is that based on my naive opinion, most of other R contexts are more for static charts, instead of interactive charts.

But I DO agree with you, it would be great to have ECharts available for all R contexts. This package is still under development, I would try my best to make it a better package. Your suggestion is of great value. You're also welcome to join me to furnish this package. Look forward to more inputs from you!
