### ISSUE TITLE
Add custom themes for ECharts 3.0 to ECharts2Shiny?

### ISSUE THREAD

**Issue by WebCodePro719** [XD-DENG/ECharts2Shiny#48]
Hi - I've created a collection of custom themes for ECharts 3.0 and I was asked on Twitter for a way to reference the themes in Shiny - Here's a link to the tweet: https://twitter.com/d8aninja/status/849694305946148864

I found your ECharts2Shiny R package googling Rstats and Shiny - I'm not familiar with either. 

Would it be at all possible for these custom themes to be incorporated into your ECharts2Shiny R package?

Here's a link to the GitHub post where I've uploaded two zip files that contain JS theme files and example charts: https://github.com/ecomfe/echarts/issues/5360

If this is something that wouldn't be difficult for you to do, I think some Rstats programmers would appreciate the extra themes.

Thanks, Janet

**Comment by XD-DENG** [comment]
Hi @WebCodePro719  thanks for approaching!

I've checked the themes you designed, they're indeed nice! I would be more than happy to add your themes into my package *ECharts2Shiny*. 

Before we do that, I'm thinking is it possible for you to select a few ones from your themes? Say 5 themes. Because I don't want to throw too many options to users, which may cause confusion.  May you compare your themes with the built-in themes of ECharts (http://echarts.baidu.com/download-theme.html) then let me know which ones would you recommend? I would suggest to pick those who're significantly different from the built-in themes. 

Please let me know your thoughts. Thanks.

**Comment by WebCodePro719** [comment]
Hi @XD-DENG - That would be awesome, thank you!

I'll let you know asap which ones I think would be the best to add.

Thanks again!

**Comment by WebCodePro719** [comment]
It took me a while, but attached is a zip file with a few custom ECharts themes that I think would be a great addition to ECharts2Shiny. These themes are significantly different from the current default ECharts 3.0 themes. The zip also includes a bunch of example charts to show what the custom themes look like. Thanks again for your willingness to add a few custom themes to ECharts2Shiny, really appreciate it!
[custom-echarts-3.0-themes.zip](https://github.com/XD-DENG/ECharts2Shiny/files/966352/custom-echarts-3.0-themes.zip)

**Comment by XD-DENG** [comment]
Thanks @WebCodePro719 . I'll update the package soon and let u know once it's done & published.

Thanks!

**Comment by XD-DENG** [comment]
Hi @WebCodePro719 .

I've added your themes into version 2.10 (commit 521fd5385570a37aab25af922b977919d8c88150). I've also added your name into the contributor list (https://github.com/XD-DENG/ECharts2Shiny/blob/master/DESCRIPTION).

I've also submitted version 2.10 to CRAN and it's under review at this moment. It should be published on CRAN very soon as well.

Thanks again for your contribution!

**Comment by WebCodePro719** [comment]
Thank you for adding my themes and for adding my name to the contributor list, I really appreciate it. Hopefully ECharts2Shiny users will like the new themes. Thanks!
