### ISSUE TITLE
The line chart can not be render by this type of table

### ISSUE THREAD

**Issue by UOTLeop** [XD-DENG/ECharts2Shiny#53]
![screen shot 2017-11-23 at 11 14 10 am](https://user-images.githubusercontent.com/24997162/33181845-af5de46a-d03f-11e7-9145-b6332af8b12b.png)
When I try to draw a bar chart using this data frame, it shows error in google console and do not return any image to the UI

**Comment by UOTLeop** [comment]
![screen shot 2017-11-23 at 11 18 21 am](https://user-images.githubusercontent.com/24997162/33181967-17547e12-d040-11e7-8a53-5e17eca5b3b6.png)

**Comment by UOTLeop** [comment]
I gradually find that the bug will happen whenever I have data more than seven rows. Which means that when I cut the table to be 7 rows, then it works fine. Could you plz give me suggestion to fix that.

**Comment by XD-DENG** [comment]
Hi @UOTLeop , Thanks for using this package and your feedback ;-)

### Issue Reason
The issue arose because of the single quotation mark `'` in your row.names. That's also why you only saw error starting from the 8th row in your data.

### Suggested Solution
Change `JUNIOR'S SHOES` to `JUNIORS SHOES`

Please let me know if this solution works.
Please also let me know if you any any further clarification. Thanks!
